### ISSUE TITLE
Question: Only sending specific errors to Sentry

### ISSUE THREAD

**Issue by lukew-cogapp** [diginov/craft-sentry-logger#15]
Hello,

We have a module that collects and deals with lots of personal information (including payment data).

For our staging site, all data is obfuscated or test data, so there's no issue in sending every error to Sentry.

However, for the production site, we would only want to send specific errors (either like an `includedExceptions` array or the ability to only manually throw an error when we want e.g. `MyCustomSentryError`. This is because we cannot guarantee that personal data isn't contained within the error until we go through a scrubbing process and it's a large code base.

Is something like this possible with this plugin? I note that the `craft-sentry` plugin [seems to support ](https://github.com/statikbe/craft-sentry/blob/master/README.md#usage)this when writing module code, as it explicitly needs the Sentry error to be thrown.

Any ideas welcome!
Thanks.

**Comment by martinleveille** [comment]
Hello @lukew-cogapp, 

I believe you can achieve the desired result with the `categories` parameter. This parameter is empty by default, which means all exception categories are sent to Sentry. If you specify classes in this parameter, only the mentioned exception categories will be sent to Sentry.

https://github.com/diginov/craft-sentry-logger?tab=readme-ov-file#categories

Since this plugin is a direct extension of a Yii Log Target, you can use all the base parameters.

https://www.yiiframework.com/doc/api/2.0/yii-log-target
